
title: ASentry's Blog 
email: ljp95453371@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ASentry.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  ASentry

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
